"""empty message

Revision ID: 71e343ada8d5
Revises: 7501e29578f2
Create Date: 2019-08-26 15:33:27.612035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e343ada8d5'
down_revision = '7501e29578f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_books', sa.Column('info', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_books', 'info')
    # ### end Alembic commands ###
